# Generated by Django 4.2.5 on 2023-10-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elec_class', models.CharField(max_length=4)),
                ('ssa', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('id_ig_ratio', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('nitrogen', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('oxygen', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('sulphur', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('density', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
            ],
        ),
    ]
