# Generated by Django 4.2.5 on 2023-10-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='predicted_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
