# Generated by Django 4.2.5 on 2023-10-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_data_predicted_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='predicted_value',
        ),
    ]
