# Generated by Django 4.2.5 on 2023-10-28 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_user_remove_data_predicted_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculate_Data',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ui.user')),
                ('elec_class', models.CharField(max_length=4)),
                ('ssa', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('id_ig_ratio', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('nitrogen', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('oxygen', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('sulphur', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('density', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('predicted_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
