# Generated by Django 4.2.5 on 2023-10-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_user_is_staff_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate_data',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculate_data',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
