# Generated by Django 4.2.5 on 2023-10-29 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
