# Generated by Django 4.2.5 on 2023-10-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('elec_class', models.CharField(max_length=4)),
                ('ssa', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('id_ig_ratio', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('nitrogen', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('oxygen', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('sulphur', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('density', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('predicted_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
