# Generated by Django 4.2.5 on 2023-10-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_datatest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate_data',
            name='density',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='calculate_data',
            name='id_ig_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='calculate_data',
            name='nitrogen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='calculate_data',
            name='oxygen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='calculate_data',
            name='predicted_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='calculate_data',
            name='ssa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='calculate_data',
            name='sulphur',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='datatest',
            name='density',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='datatest',
            name='id_ig_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='datatest',
            name='nitrogen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='datatest',
            name='oxygen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='datatest',
            name='predicted_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='datatest',
            name='ssa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='datatest',
            name='sulphur',
            field=models.FloatField(default=0.0),
        ),
    ]
