# Generated by Django 4.2.5 on 2023-11-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0012_alter_calculate_data_density_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='DataTest',
        ),
        migrations.RemoveField(
            model_name='calculate_data',
            name='elec_class',
        ),
        migrations.AddField(
            model_name='calculate_data',
            name='ph',
            field=models.FloatField(default=0.0),
        ),
    ]
